on:
  push:
    paths:
      - packages/*/package-lock.json
      - packages/*/LICENSE
      - packages/*/LICENSES
      - packages/*/LICENSES.md
      - .github/workflows/checks.yaml
      - .github/workflows/license-check.yaml

jobs:
  check-licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      -
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            packages/**/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Check player
        uses: ./.github/workflows/license-check.yaml
        with:
          package: gplayer
      - name: Check plugins
        uses: ./.github/workflows/license-check.yaml
        with:
          package: plugins
      - name: Check utils
        uses: ./.github/workflows/license-check.yaml
        with:
          package: utils
