on:
  workflow_call:
    inputs:
      package:
        type: string
        description: The package to check (gplayer, plugins)
        required: true

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      -
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            packages/${{ inputs.package }}/package-lock.json
      - name: check files
        run: |
          ls packages/${{ inputs.package }}
      - name: Install dependencies
        run: |
          npm ci
          npm ci -C packages/${{ inputs.package }}
      - name: Check licenses
        run: npm run check:license packages/${{ inputs.package }}
