on:
  workflow_call:
    inputs:
      package:
        type: string
        description: The package to check (gplayer, plugins)
        required: true

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: packages/${{ inputs.package }}/package-lock.json
      - name: Install dependencies
        # Note that the root dependencies must be installed first
        run: npm ci -C packages/${{ inputs.package }}
      - name: Check licenses
        run: npm run check:license packages/${{ inputs.package }}
